/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_v1_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Summary */
        get: operations["analytics_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivitiesResponse */
        ActivitiesResponse: {
            freshness: components["schemas"]["FreshnessMetadata"];
            /** Items */
            items: components["schemas"]["Activity"][];
        };
        /** Activity */
        Activity: {
            /** Average Heartrate */
            average_heartrate?: number | null;
            /** Average Speed */
            average_speed: number;
            /** Distance */
            distance: number;
            /** Elevation Gain */
            elevation_gain?: number | null;
            /** Location Country */
            location_country?: string | null;
            /** Moving Time */
            moving_time: string;
            /** Name */
            name: string;
            /** Run Id */
            run_id: number;
            /** Start Date */
            start_date: string;
            /** Start Date Local */
            start_date_local: string;
            /** Streak */
            streak: number;
            /** Subtype */
            subtype: string;
            /** Summary Polyline */
            summary_polyline?: string | null;
            /** Type */
            type: string;
        };
        /** AnalyticsSummary */
        AnalyticsSummary: {
            /** Average Heartrate */
            average_heartrate?: number | null;
            /** Total Activities */
            total_activities: number;
            /** Total Distance */
            total_distance: number;
            /** Total Moving Time Seconds */
            total_moving_time_seconds: number;
        };
        /** AnalyticsSummaryResponse */
        AnalyticsSummaryResponse: {
            freshness: components["schemas"]["FreshnessMetadata"];
            summary: components["schemas"]["AnalyticsSummary"];
        };
        /** FreshnessMetadata */
        FreshnessMetadata: {
            /**
             * Completeness
             * @enum {string}
             */
            completeness: "complete" | "partial" | "unavailable";
            /** Last Sync At */
            last_sync_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_activities_api_v1_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitiesResponse"];
                };
            };
        };
    };
    analytics_summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummaryResponse"];
                };
            };
        };
    };
}
